run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    # maligned # deprecated 1.38 but govet-fieldalignment not usuable
    - interfacer # deprecated 1.38
    - scopelint # deprecated 1.39
    - golint # deprecated 1.41
    - exhaustivestruct # deprecated 1.46
    # ifshort deprecated 1.48 but no replacement
    - deadcode # deprecated 1.49
    - structcheck # deprecated 1.49
    - varcheck # deprecated 1.49
    - funlen
    - dupl
    - wsl
    - gomnd
    - goerr113 
    - nestif
    - exhaustruct
    - paralleltest
    - cyclop
    - forcetypeassert
    - gomoddirectives
    - varnamelen
    - nonamedreturns
    - maintidx
    - execinquery
    - nosnakecase
    - musttag
    - depguard
    - gosec
    - inamedparam
    - ireturn
linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/jeremmfr/terraform-provider-junos/)
      - default
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 180
  goconst:
    # Minimum occurrences of constant string count to trigger issue.
    min-occurrences: 25
    # Ignore test files.
    ignore-tests: true
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 100
  gofumpt:
    module-path: github.com/jeremmfr/terraform-provider-junos
    # Choose whether to use the extra rules.
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
issues:
  exclude-rules:
    - text: "github.com/jeremmfr/terraform-provider-junos/internal"
      linters:
        - wrapcheck
    - path: "internal/providersdk/"
      linters:
        - goconst
    - text: "string `description \"` has "
      linters:
        - goconst
